[package]
name = "gradients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

custos = {path = "../../custos", features=["opencl"]}
custos-math = {path = "../../custos-math", features=[]}
purpur = {path = "../../purpur"}

gradients-derive = {path = "../gradients-derive"}


rand = "*"

#custos = {git = "https://github.com/elftausend/custos.git"}
#custos-math = {git = "https://github.com/elftausend/custos-math.git"}
#purpur = {git = "https://github.com/elftausend/purpur.git"}

[dev-dependencies]
graplot = "0.1.16"