[package]
name = "gradients"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#purpur = {git = "https://github.com/elftausend/purpur.git"}
[dependencies]

custos = {path = "../../custos"}
custos-math = {path = "../../custos-math"}
gradients-derive = {path = "../gradients-derive"}

purpur = {path = "../../purpur"}
rand = "*"

#custos = {git = "https://github.com/elftausend/custos.git"}
#custos-math = {git = "https://github.com/elftausend/custos-math.git"}
